
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    component: kibana
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: kibana
  template:
    metadata:
      labels:
        component: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.17.27
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_URL
              value: 'http://elasticsearch.elastic.svc.cluster.local:9200'
          resources:
            requests:
              memory: 500Mi
              cpu: '0.5'
            limits:
              memory: 2Gi
              cpu: '2'
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    component: kibana
spec:
  ports:
  - port: 5601
  selector:
    component: kibana
