apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  labels:
    component: fluentd
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/access.log
      pos_file /tmp/app.logs.pos
      tag app.logs
      <parse>
        @type json
      </parse>
    </source>
    <match app.logs>
      @type elasticsearch
      host elasticsearch.elastic.svc.cluster.local
      port 9200
      logstash_format true
      logstash_prefix fluentd
      flush_interval 1s
    </match>
    <match app.logs>
      @type opensearch
      host opensearch.opensearch.svc.cluster.local
      port 9200
      logstash_format true
      logstash_prefix fluentd
      flush_interval 1s
    </match>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  labels:
    component: busybox
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: busybox
  template:
    metadata:
      labels:
        component: busybox
    spec:
      containers:
        - name: busybox
          image: busybox
          args:
            - sh
            - -c
            - >
              while true;
              do
                echo '{"date":"'$(date)'", "hello":"world", "log": "filebeat log"}' >> /var/log/access.log;
                sleep 10;
              done
          volumeMounts:
            - name: log
              mountPath: /var/log
          resources:
            requests:
              memory: 500Mi
              cpu: '0.5'
            limits:
              memory: 500Mi
              cpu: '0.5'
        - name: fluentd
          image: hub.opensciencegrid.org/mwestphall/fluentd
          volumeMounts:
            - name: fluentd-config
              mountPath: /fluentd/etc
            - name: log
              mountPath: /var/log
          resources:
            requests:
              memory: 500Mi
              cpu: '0.5'
            limits:
              memory: 500Mi
              cpu: '0.5'
      volumes:
        - name: log
          emptyDir: {}
        - name: fluentd-config
          configMap:
            name: fluentd-config
