apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  labels:
    component: fluentd
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/access.log
      pos_file /tmp/app.logs.pos
      tag app.logs
      <parse>
        @type json
        time_key time
        time_format %iso8601
      </parse>
    </source>

    <filter app.logs>
      @type record_transformer
      <record>
        hostname "#{Socket.gethostname}"
      </record>
    </filter>

    <match app.logs>
      @type elasticsearch
      host elasticsearch.elastic.svc.cluster.local
      port 9200
      logstash_format true
      logstash_prefix fluentd
      flush_interval 1s
    </match>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-log-client
  labels:
    component: go-log-client
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: go-log-client
  template:
    metadata:
      labels:
        component: go-log-client
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: go-log-client
          image: hub.opensciencegrid.org/mwestphall/go-log-client
          args:
            - stream
          env:
            - name: LOG_PATH
              value: /var/log/access.log
          volumeMounts:
            - name: log
              mountPath: /var/log
          resources:
            requests:
              memory: 500Mi
              cpu: '0.5'
            limits:
              memory: 500Mi
              cpu: '0.5'
        - name: fluentd
          image: hub.opensciencegrid.org/mwestphall/fluentd
          volumeMounts:
            - name: fluentd-config
              mountPath: /fluentd/etc
            - name: log
              mountPath: /var/log
          resources:
            requests:
              memory: 500Mi
              cpu: '0.5'
            limits:
              memory: 500Mi
              cpu: '0.5'
      volumes:
        - name: log
          emptyDir:
            sizeLimit: 5Mi
        - name: fluentd-config
          configMap:
            name: fluentd-config
