services:
  tests:
    build:
      context: .
      dockerfile: tests.Dockerfile
    volumes:
      - testvol:/mnt/small-test-vol

volumes:
  testvol:
    driver_opts:
      type: "tmpfs"
      o: "size=24K"
      device: "tmpfs"
