{
 "title": "Status Code vs Time",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Sample Log Generator Analytics\n"
   }
  },
  { "title": "Ratio of Status Code Responses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Status Code Ratios",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "alias": "RecordCount",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status_code: *",
     "timeField": "@timestamp"
    },
    {
     "alias": "Count500",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status_code: \"500\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Count200",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status_code: \"200\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Recent Error Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Recent Error Logs",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "status_code: \"500\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Status Code Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Query Response Codes vs Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "alias": "count_200",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status_code: \"200\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count_400",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status_code: \"400\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count_500",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status_code: \"500\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Status Code By Endpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Query Response Codes vs Time for /staging",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "targets": [
    {
     "alias": "count_200",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status: \"200\" AND path: \"/staging\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count_400",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status: \"400\" AND path: \"/staging\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count_500",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status: \"500\" AND path: \"/staging\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Query Response Codes vs Time for /development",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "targets": [
    {
     "alias": "count_200",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status: \"200\" AND path: \"/development\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count_400",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status: \"400\" AND path: \"/development\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count_500",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status: \"500\" AND path: \"/development\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Query Response Codes vs Time for /test",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "targets": [
    {
     "alias": "count_200",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status: \"200\" AND path: \"/test\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count_400",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status: \"400\" AND path: \"/test\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count_500",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status: \"500\" AND path: \"/test\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}