log_level: INFO # Log level (e.g., DEBUG, INFO, WARN, ERROR)

console_output: # Console output settings
  enabled: true # Enable or disable console output
  json_object: false # If true, output JSON objects; disables colors
  colors: true # Enable color-coded logs (ignored if json_object is true)

file_output: # File output settings
  enabled: true # Enable or disable file output
  file_path: /var/log/chtc/app.log # Path to the log file
  max_file_size: 100 # Max file size in MB
  max_backups: 5 # Number of backups to retain
  max_age_days: 30 # Maximum age of logs in days
