{
 "title": "Status Code vs Time",
 "time": { "from": "2025-02-10T17:13:44.280Z", "to": "2025-02-10T20:00:19.432Z" },
 "panels": [
  {
   "title": "Query Response Codes vs Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "count_200",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status_code: \"200\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count_400",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status_code: \"400\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count_500",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status_code: \"500\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Query Response Codes vs Time for /test",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "count_200",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status: \"200\" AND path: \"/test\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count_400",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status: \"400\" AND path: \"/test\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count_500",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status: \"500\" AND path: \"/test\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Query Response Codes vs Time for /staging",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "count_200",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status: \"200\" AND path: \"/staging\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count_400",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status: \"400\" AND path: \"/staging\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count_500",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status: \"500\" AND path: \"/staging\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Query Response Codes vs Time for /staging",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "alias": "count_200",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status: \"200\" AND path: \"/development\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count_400",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status: \"400\" AND path: \"/development\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "count_500",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status: \"500\" AND path: \"/development\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}