name: Test

on:
  push:
    branches:
      - "**" # Triggers on push to any branch
  pull_request:
    branches:
      - "**" # Triggers on pull requests targeting any branch
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.23
      options: --shm-size=24kb # Need to set a low shm size for 'out of storage' tests

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Set up Go (minimum version 1.20)
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.20"

      # Cache dependencies
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Create an unprivileged user to run tests as
      - name: Create non-root user
        run: |
          useradd gouser
          mkdir -p /home/gouser/.cache/go-build
          chown gouser /home/gouser/.cache/go-build/

      # Run tests unprivileged
      - name: Run tests
        run: su -c 'go test ./... -v' gouser
